// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3oYgNX6q_220g6w9bagscj-SNFuOQjUw',
    appId: '1:945192440891:web:05b9f3eb420905f0bff81e',
    messagingSenderId: '945192440891',
    projectId: 'notecheak',
    authDomain: 'notecheak.firebaseapp.com',
    storageBucket: 'notecheak.appspot.com',
    measurementId: 'G-RJ6SB342SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5lnk3NjXVE9HgI6Irut_5iyCzVoGbX_I',
    appId: '1:945192440891:android:d9da6c4ded2f1969bff81e',
    messagingSenderId: '945192440891',
    projectId: 'notecheak',
    storageBucket: 'notecheak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzGLgZwf7WlEIe5U5HyRaeAaqGJbJgkvI',
    appId: '1:945192440891:ios:62cfd1c0b2f44573bff81e',
    messagingSenderId: '945192440891',
    projectId: 'notecheak',
    storageBucket: 'notecheak.appspot.com',
    iosBundleId: 'com.example.notecheak',
  );
}
